version: "3.9"
services:
  db-payments:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - src/.env
    ports:
      - "5436:5432"
    networks:
      - mc_network
  web-payments:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8500
    volumes:
      - ./src:/app/src
    ports:
      - "8500:8500"
    networks:
      - mc_network
    depends_on:
      - db-payments
networks:
  mc_network:
    external: true